# Generated by Django 4.2 on 2025-03-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
